platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FirebaseExample' do
  pod 'Firebase/Core', '~> 4.0.2'
  pod 'Firebase/Auth', '~> 4.0.2'
  pod 'Firebase/Database', '~> 4.0.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ENABLE_TESTABILITY'] = 'NO'
    end
  end
end
